### ISSUE TITLE
Running two boxes at once?

### ISSUE THREAD

**Issue by snigel1** [scotch-io/scotch-box#185]
Hi,

I have set up several instances of scotch box. Works great as long as i only run one at a time, but i wonder if it is possible to have two or more running?

When i vagrant up a second box, i get this error:
```

Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 2222 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 22, host: 1234
```

Adding config.vm.network :forwarded_port, guest: 22, host: 81 does not work either.

I understand i can run multiple vhosts on a single box, but it would be really great to be able to run separate boxes at once, so i can run two vagrant shares

**Comment by syntacticNaCl** [comment]
Hi @snigel1,

You can add "auto_correct: true" to the end of your config.vm.network line so it would read like this:

`config.vm.network :forwarded_port, guest: 22, host: 1234, auto_correct: true`

That should fix the collision issue.

You can also just change the IP in one of the box's Vagrantfile to something like 192.168.33.20. That way you can access box 1 at 192.168.33.10 and the second at 192.168.33.20 (or whatever IPs you currently have set).

You could then add it to your hosts file. That way you wouldn't have to navigate to those IPs each time. For example:

```
192.168.33.10 devbox1.local
192.168.33.20 devbox2.local
```

**Comment by snigel1** [comment]
Thanks but i still cant spin up one at 192.168.0.10 when one is running at 192.168.0.12 already, even if i add auto_correct: true to the second box's Vagrantfile

**Comment by syntacticNaCl** [comment]
Hmm... Could you by chance post your Vagrantfile's? I would like to see if I can get it to do the same thing on my end.

**Comment by snigel1** [comment]
Sure, here:

#1:

`Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.12"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
    
    config.trigger.before :up do
      info "ip: 192.168.33.12"
	end
    
    config.trigger.before :destroy do
      info "Dumping the database before destroying the VM..."
      run_remote  "bash /var/www/db/db_dump.sh"
	end
	
	config.trigger.before :suspend do
      info "Dumping the database before suspending the VM..."
      run_remote  "bash /var/www/db/db_dump.sh"
	end
    

end`

and

`# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

    config.vm.network :forwarded_port, guest: 22, host: 1234, auto_correct: true
    
    config.trigger.before :up do
      info "ip: 192.168.33.10"
	end

end
`

**Comment by syntacticNaCl** [comment]
I still am not able to reproduce it. Found something when doing some research though. Are you on MacOS? Seems that with explicitly forwarding by setting an id of "ssh" people have gotten this issue resolved (for MacOS). Try something like this: 
`config.vm.network :forwarded_port, guest: 22, host: 1234, id: "ssh", auto_correct: true`

This was suggested here: http://stackoverflow.com/questions/24127852/vagrant-cannot-forward-the-specified-ports-on-this-vm

**Comment by snigel1** [comment]
Thanks. Didnt work either at first. But i ran vagrant reload on both machines and now i have them both up at the same time, so whatever sovled it, it needed a reload for changes to take effect it seems

**Comment by syntacticNaCl** [comment]
Cool. Glad that worked for you.
